trigger:
- none

pool:
  vmImage: 'macos-latest'

jobs:
- job: chromeLocalTest
  steps:
    - script: npm install
      displayName: 'NPM Install Dependencies'

    - script: npm run start-web
      displayName: 'Start Automated Tests'

    - script: |
        npm run clean-report
      condition: always()
      displayName: 'Create Allure Report'

    - task: ArchiveFiles@2
      displayName: 'Compress Allure Report'
      condition: always()
      inputs:
        rootFolderOrFile: 'allure-report'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: 'allure-report/allure-report.zip'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Allure Report'
      condition: always()
      inputs:
        targetPath: 'allure-report/allure-report.zip'
        artifactName: allure-report-mobile

    - task: PublishTestResults@2
      displayName: 'JUnit Report'
      condition: always()
      inputs:
        testResultsFormat: "JUnit"
        testResultsFiles: "results*.xml"
        searchFolder: "./junit-results"
        failTaskOnFailedTests: true
    - script: |
      npm run generate-report
      displayName: 'npm run cucumber-reports'
      workingDirectory: '$(Build.SourcesDirectory)'  #working in this directory

      condition: succeededOrFailed()

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/reports'
        #Contents: '***/reports' #folder containing files
        TargetFolder: '$(Build.ArtifactStagingDirectory)' #to this folder
        flattenFolders: true
      condition: succeededOrFailed()    

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Cucumber Report'
        publishLocation: 'Container'
      condition: succeededOrFailed()
